### ISSUE TITLE
CI/CD design for all environments

### ISSUE THREAD

**Issue by evillgenius75** [retaildevcrews/helium#102]
Design review for unified ci/cd using GitHub Actions.

**Comment by evillgenius75** [comment]
# Design Review

## Introduction

The goal of this implementation is to consolidate all Continuous Integration and Delivery(CI/CD) into one platform with a unified process across all helium language sub-projects. The nature of the project is that all applications are to be packaged as containers using docker technology and stored in a repository that can be used to centrally distribute the application. The CI/CD process must also include a strategy for tagging, versioning, testing and notification of new releases if possible. Every possible effort should be made to make the process useable across many different scenarios with security, adaptability and developer experience as top of mind in the design.

## System Overview

The implementation of the CI/CD system will leverage GitHub Actions as a method of automation as it integrates natively with GitHub repositories, the preferred version control environment that projects the release teams use. The system process will allow for automatic build and push of the container image to one or many container repositories to be consumed by systems. All authentication mechanisms will use a secure store to authenticate the system to other systems with the minimal scope needed for functionality. The process will be triggered based on normal development tasks within github repositories and will need to log accordingly and properly let users know that the process is successful. The system will allow for staged releases that map to different stages of the release process including:

* Iterative test builds

* Beta builds based on PR creation

* Stable and Version tagged builds based on commits to Master branch of source respositories

## Design Considerations

The system will need to take into consideration a few assumptions on the current release process used. Properly documenting the system will allow for changes as needed when processes are refinde during the normal course of process review.

### Assumptions and Dependencies

* All respostitories requiring CI/CD will be for Docker based system and contain a Dockerfile and the requisite source code to build

* All source code is placed in a `src` directory at the root of the repository

* All requisite docuements are stored in a `docs` directory at the root of the repository

* Only changes to Dockerfile and files in the `src` directory will trigger a build

* All Developers will follow a specific tagging and PR process to allow for the proper CI/CD tasks to complete

* The CI/CD tool will push images to one or more Container registries and the required registries have proper authentication and authorization configured

* The reositories will maintain a semVer (i.e Major.Minor.Patch) tagging process that will follow conventions where breaking API changes require a change in Major version number (i.e. 1.0.0 to 2.0.0)

### General Constraints

### Goals and Guidelines

* On creation of a PR a container build is created based on the branch of code the PR is for to allow for testing of PR code changes against a test system. The image will be tagged with a `{BranchName:PR}` nomenclature and placed in a subrepository `test/`. Only once the image has been tested and proof (i.e. log files, E2E test logs) has been added to PR will the PR be merged to Master by approvers.

* On commit of PR to Master, a Version tag must be updated and the CI/CD tooling will create a new image with `{stable}` tag and `{semVer}` tag. If the tag's semver increases the major number (i.e X.0.0) then a `{beta}` tag will be created only as this is a breaking API change. Once the code is tested against the E2E system for 72 hours will a PR be cut to change the semVer to increase the minor version to x.1.0 which will trigger a CI/CD to create `{stabe}` and `{semVer}` tagged images.

* The E2E testing systems will enable webhook based CD mechanism targeting the correct tag for the environment.

### Development Methods

* Already existing Github Action modules or if need a custom module can be written in any preferred language

## Architectural Strategies

### Developer Friendly

The developer should have little to no interaction with the CI/CD system besides creating the requisite webhooks on the recieving system. Only normal Github operations of commits, PRs, tags, versioning should trigger the requisite flows.

### Reusable

The proposed solution should work across any repository that will require a docker image build as long as the assumptions and depedencies are met.

### Secure

The system will follow the best practices for secure authorization and authentication with least privelaged access when possible.

## System Architecture

### Github Action Workflow

```yaml
name: Docker CI

on:
  push:
    branches:
      - master

    paths:
      - 'src/**'
      - 'Dockerfile*'

    tags:
      - v*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Login to registry
      run: |
        # Login to registry

        # You must add the following secrets to github
        #    DOCKER_USER  - your dockerhub user name
        #    DOCKER_PAT   - the personal access token for dockerhub
        #    DOCKER_REPO  - the docker repository name in the form: organization/repository

        ## login to dockerhub
        echo "${{ secrets.DOCKER_PAT }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Build Container
      run: docker build . --file Dockerfile --tag image

    - name: Docker Push
      run: |
        # Tag and push the docker image

        IMAGE_ID=${{ secrets.DOCKER_REPO }}

        # tag the image with :beta
        docker tag image $IMAGE_ID:beta

        # Tag image based on repo tag if a github label
        if [[ "${{ github.ref }}" == "refs/tags/"* ]]
        then

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          VERSION=$(echo $VERSION | sed -e 's/^v//')

          docker tag image $IMAGE_ID:$VERSION
          docker tag image $IMAGE_ID:stable
        fi

        # Push to the repo
        docker push $IMAGE_ID
```

## Policies and Tactics

### Design Review Checklist

- [ ] Design Review Meeting Scheduled
- [ ] Design Review approved by team consensus
- [ ] Sprint Schedule is agreed to according to milestone and project
- [ ] Tasks created as Issues are created in main project and Assigned the correct size, priority level and milestone

## Detailed System Design

### module-1 name or description

## Glossary
